---
- name: Setup Proxy Server
  hosts: vtsingle-proxy-server
  become: yes
  tasks:
    - name: Install squid proxy
      ansible.builtin.apt:
        name: squid
        state: present
        update_cache: yes

    - name: Configure squid to allow all
      ansible.builtin.copy:
        content: |
          http_port 3128
          acl localnet src 0.0.0.0/0
          http_access allow localnet
          http_access allow localhost
          http_access deny all
        dest: /etc/squid/squid.conf
        mode: '0644'

    - name: Start squid service
      ansible.builtin.service:
        name: squid
        state: started
        enabled: yes

- name: Converge
  hosts: test_target
  become: yes
  vars:
    victoriatraces_install_download_to_control: false
    vm_proxy_http: "http://vtsingle-proxy-server:3128"
    vm_proxy_https: "http://vtsingle-proxy-server:3128"
  tasks:
    - name: "Include vtsingle"
      ansible.builtin.include_role:
        name: "vtsingle"
