---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  ansible.builtin.command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  ansible.builtin.set_fact:
    victoriatraces_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[1] }}"

- name: Check if VictoriaTraces is installed
  ansible.builtin.stat:
    path: /usr/local/bin/victoria-traces-prod
  changed_when: false
  check_mode: false
  register: victoriatraces_is_installed

- name: Check current VictoriaTraces version
  ansible.builtin.command: /usr/local/bin/victoria-traces-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: victoriatraces_current_version
  when: victoriatraces_is_installed.stat.exists | bool

- name: Get latest VictoriaTraces version via GitHub redirect
  ansible.builtin.uri:
    url: "{{ victoriatraces_repo_url }}/releases/latest"
    method: HEAD
    return_content: false
    follow_redirects: false
    status_code: 302,200
  register: gh_redirect
  when: victoriatraces_version == "latest"

- name: Extract version from Location header
  ansible.builtin.set_fact:
    victoriatraces_version: "{{ (gh_redirect.location | regex_search('/releases/tag/(v[0-9].*)', '\\1'))[0] }}"
  when: victoriatraces_version == "latest"
