---
- name: gather facts
  setup:

- name: Create data directory
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - "{{ vmstorage_host_path }}"
  - "{{ vm_conf_host_path }}"

- name: "ensure {{ vm_role }} unit file"
  notify: "restart service {{ vm_role }}"
  template:
    src: "{{ vm_role }}.service.j2"
    dest: "/etc/systemd/system/{{ vm_role }}.service"

- name: "ensure {{ vm_role }} environment_file"
  template:
    src: vm_environment.j2
    dest: "{{ environment_file_path }}/{{ vm_role }}"
  notify: "restart service {{ vm_role }}"
  when: not (use_environment | bool)

- name: Execute handlers
  meta: flush_handlers

- name: start services
  systemd:
    name: "{{ vm_role }}"
    daemon_reload: yes
    enabled: yes
    state: started
