- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vlagent_license_key != "" or vlagent_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vlagent_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vlagent_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vlagent_enterprise | bool
    - vlagent_license_key != ""

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vlagent_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vlagent_enterprise | bool
    - vlagent_license_key_file != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vlagent_service_args: "{{ vlagent_service_args | combine({'license': vlagent_license_key}) }}"
  when:
    - vlagent_enterprise | bool
    - vlagent_license_key != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vlagent_service_args: "{{ vlagent_service_args | combine({'licenseFile': vlagent_license_key_file}) }}"
  when:
    - vlagent_enterprise | bool
    - vlagent_license_key_file != ""
