---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vmagent"
      vars:
        vmagent_enterprise: true
        vmagent_license_key: "{{ lookup('env', 'VM_LICENSE_KEY') }}"
        vmagent_license_key_file: "{{ '' if lookup('env', 'VM_LICENSE_KEY') else '/tmp/vm-license' }}"
        vmagent_service_args:
          "remoteWrite.url":
            - "http://url1/api/v1/write"
            - "http://url2/api/v1/write"
          "remoteWrite.tmpDataPath": /tmp/vmagent
      ansible.builtin.include_role:
        name: "vmagent"
