---
# Upstream issue, see: https://github.com/geerlingguy/docker-rockylinux9-ansible/issues/6
# TODO: remove when fixed upstream
- name: Fix /etc/shadow permissions if SELinux is enabled
  hosts: all
  become: yes
  tasks:
    - name: Debugging
      changed_when: false
      ansible.builtin.shell:
        cmd: |
          ls -l /etc/shadow
          chmod 0640 /etc/shadow || true
          ls -l /etc/shadow
      when:
        - ansible_selinux is defined
        - ansible_selinux.status == "enabled"

- name: Setup Proxy Server
  hosts: vmstorage-proxy-server
  become: yes
  tasks:
    - name: Install squid proxy
      ansible.builtin.apt:
        name: squid
        state: present
        update_cache: yes

    - name: Configure squid to allow all
      ansible.builtin.copy:
        content: |
          http_port 3128
          acl localnet src 0.0.0.0/0
          http_access allow localnet
          http_access allow localhost
          http_access deny all
        dest: /etc/squid/squid.conf
        mode: '0644'

    - name: Start squid service
      ansible.builtin.service:
        name: squid
        state: started
        enabled: yes

- name: Converge
  hosts: test_target
  become: yes
  vars:
    vmstorage_install_download_to_control: false
    vm_proxy_http: "http://vmstorage-proxy-server:3128"
    vm_proxy_https: "http://vmstorage-proxy-server:3128"
  tasks:
    - name: "Include vmstorage"
      ansible.builtin.include_role:
        name: "vmstorage"
