---
- name: Converge
  hosts: all
  become: yes
  vars:
    vlagent_install_download_to_control: true
  tasks:
    - name: "Include vlagent"
      vars:
        vlagent_service_args:
          "remoteWrite.url":
            - "http://url1/internal/insert"
          "remoteWrite.tmpDataPath": /tmp/vlagent
      ansible.builtin.include_role:
        name: "vlagent"
