---
- name: Configure env
  when: victoriametrics_service_envflag_enabled | bool
  block:
    - name: Check envfile presence
      ansible.builtin.stat:
        path: "{{ victoriametrics_service_envflag_file }}"
      register: envfile_state

    - name: Setup envfile
      ansible.builtin.file:
        state: touch
        path: "{{ victoriametrics_service_envflag_file }}"
        owner: root
        group: root
        mode: 0644
        access_time: preserve
      notify: Restart VictoriaMetrics service
      when: envfile_state.stat.exists is defined and not envfile_state.stat.exists

- name: Copy VictoriaMetrics systemd unit file
  ansible.builtin.template:
    src: victoriametrics.service.j2
    dest: /etc/systemd/system/victoriametrics.service
    owner: root
    group: root
    mode: 0644
  register: config_template
  no_log: True

- name: Daemon-reload VictoriaMetrics service
  become: true
  notify: Restart VictoriaMetrics service
  ansible.builtin.systemd:
    daemon_reload: true
    name: victoriametrics
  when: config_template is changed  # noqa: no-handler

- name: Ensure VictoriaMetrics service is enabled on boot
  become: true
  ansible.builtin.systemd:
    name: victoriametrics
    enabled: true

- name: Configure credentials
  when: victoriametrics_backup_enabled | bool
  block:
    - name: Create aws credentials dir
      become: true
      ansible.builtin.file:
        path: ~/.aws
        state: directory
        mode: 0755

    - name: Create aws config file
      become: true
      ansible.builtin.copy:
        dest: ~/.aws/config
        mode: 0644
        content: |
          [default]
          region = eu-west-1
          output = json

    - name: Template credentials file
      ansible.builtin.template:
        src: creds.j2
        dest: ~/.aws/credentials
        mode: 0644

    - name: Set proxy config
      ansible.builtin.set_fact:
        _victoria_backup_proxy: "http_proxy={{ http_proxy }} https_proxy={{ http_proxy }} "
      when:
        - victoriametrics_backup_proxy_enable
        - http_proxy is defined

    - name: Configure cron
      ansible.builtin.cron:
        name: "backup victoriametrics data"
        user: root
        state: present
        minute: "{{ victoriametrics_backup_cron_minute }}"
        hour: "{{ victoriametrics_backup_cron_hour }}"
        day: "{{ victoriametrics_backup_cron_day }}"
        weekday: "{{ victoriametrics_backup_cron_weekday }}"
        month: "{{ victoriametrics_backup_cron_month }}"
        job: "{{ _victoria_backup_proxy | default('') }} /usr/local/bin/vmbackup-prod -snapshot.createURL=http://localhost:8428/snapshot/create {% if victoriametrics_backup_custom_s3_endpoint != '' %} -customS3Endpoint {{ victoriametrics_backup_custom_s3_endpoint }} {% endif %} -storageDataPath {{ victoriametrics_data_dir }} -dst {{ victoriametrics_backup_destination }}/$(date +\\%Y-\\%m-\\%d)"

- name: Delete cron if backup disabled
  ansible.builtin.cron:
    name: "backup victoriametrics data"
    user: root
    minute: "{{ victoriametrics_backup_cron_minute }}"
    hour: "{{ victoriametrics_backup_cron_hour }}"
    day: "{{ victoriametrics_backup_cron_day }}"
    weekday: "{{ victoriametrics_backup_cron_weekday }}"
    month: "{{ victoriametrics_backup_cron_month }}"
    state: absent
  when: not victoriametrics_backup_enabled | bool
