---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  ansible.builtin.command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  ansible.builtin.set_fact:
    victoriametrics_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- name: Check if VictoriaMetrics is installed
  ansible.builtin.stat:
    path: /usr/local/bin/victoria-metrics-prod
  changed_when: false
  check_mode: false
  register: victoriametrics_is_installed

- name: Check current VictoriaMetrics version
  ansible.builtin.command: /usr/local/bin/victoria-metrics-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: victoriametrics_current_version
  when: victoriametrics_is_installed.stat.exists | bool
