---
- name: Assert usage of systemd or upstart as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  ansible.builtin.command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  when: ansible_service_mgr == 'systemd'

- name: Set systemd version fact
  ansible.builtin.set_fact:
    vminsert_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[1] }}"
  when: ansible_service_mgr == 'systemd'

- name: Check if vminsert is installed
  ansible.builtin.stat:
    path: /usr/local/bin/vminsert-prod
  changed_when: false
  check_mode: false
  register: vminsert_is_installed

- name: Check current vminsert version
  ansible.builtin.command: /usr/local/bin/vminsert-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: vminsert_current_version
  when: vminsert_is_installed.stat.exists | bool

- name: Get latest VMinsert version via GitHub redirect
  ansible.builtin.uri:
    url: "{{ vminsert_repo_url }}/releases/latest"
    method: HEAD
    return_content: false
    follow_redirects: false
    status_code: 302,200
  register: gh_redirect
  when: vminsert_version == "latest"

- name: Extract version from Location header
  ansible.builtin.set_fact:
    vminsert_version: "{{ (gh_redirect.location | regex_search('/releases/tag/(v[0-9].*)', '\\1'))[0] }}"
  when: vminsert_version == "latest"
