---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vmalert"
      vars:
        vic_vm_alert_enterprise: true
        vic_vm_alert_license_key: "{{ lookup('env', 'VM_LICENSE_KEY') }}"
        vic_vm_alert_license_key_file: "{{ '' if lookup('env', 'VM_LICENSE_KEY') else '/tmp/vm-license' }}"
      ansible.builtin.include_role:
        name: "vmalert"
