---
- name: Converge
  hosts: all
  become: yes
  vars:
    victorialogs_enterprise: true
    victorialogs_license_key: "{{ lookup('env', 'VM_LICENSE_KEY') }}"
    victorialogs_license_key_file: "{{ '' if lookup('env', 'VM_LICENSE_KEY') else '/tmp/vl-license' }}"
    victorialogs_data_dir: "/tmp/victoria-logs/"
    victorialogs_service_envflag_enabled: true
    victorialogs_service_envflag_data:
      - "syslog_listenAddr_tcp=127.0.0.1:12345"
    victorialogs_service_args:
      storageDataPath: "{{ victorialogs_data_dir }}"
  tasks:
    - name: "Include vlsingle"
      ansible.builtin.include_role:
        name: "vlsingle"
