---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include vlagent"
      vars:
        vlagent_enterprise: true
        vlagent_license_key_file: "/tmp/vm-license"
        vlagent_service_args:
          "remoteWrite.url":
            - "http://url1/internal/insert"
          "remoteWrite.tmpDataPath": /tmp/vlagent
      ansible.builtin.include_role:
        name: "vlagent"
