name: 'Molecule Test'

permissions:
  contents: read
  actions: write

on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  test-debian:
    name: 'Test - debian'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Cache .venv directory
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Converge
        run: |
          make init-venv
          make -j$(( $(nproc) * 2 )) molecule-converge
          make -j$(( $(nproc) * 2 )) molecule-converge-integration
